### ISSUE TITLE
Add image, description fields to Gesture

### ISSUE THREAD

**Issue by rcnewman** [tmedeiros/gesture_collection#9]
A user should be able to see a description of a gesture to understand how to perform it with an accelerometer enabled device.

Add image and description fields to the Gesture object.

**Comment by Jagdish05** [comment]
<img width="297" alt="Screenshot 2020-11-17 at 3 53 14 PM" src="https://user-images.githubusercontent.com/20869295/99456207-a033aa00-28ee-11eb-8ee1-2873e59a2c9d.png">

is there anything need to change or update ?
